{% set version = "0.1-8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-png
  version: {{ version|replace("-", "_") }}

source:
  fn: png_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/png_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/png/png_{{ version }}.tar.gz
  sha256: 5a36fabb6d62ba2533d3fc4cececd07891942cfb76fe689ec0d550d08762f61c

build:
  merge_build_host: true  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}gzip              # [win]
    - {{ posix }}tar               # [win]
  host:
    - r-base
    - libpng   # [not win]
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('png')"           # [not win]
    - "\"%R%\" -e \"library('png')\""  # [win]

about:
  home: http://www.rforge.net/png/
  license: GPL-2.0-only OR GPL-3.0-only
  summary: This package provides an easy and simple way to read, write and display bitmap images stored in the PNG format. It can read and write both files and in-memory raw vectors.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
